---
title: "2023_2_SeedSeedlingJAGS"
output: html_document
date: "2023-03-20"
---

10 years Categorical Pace and parity
```{r}
# specify model in BUGS language   
model10yearSeed <- 
  paste("
      model {
        # Likelihood:
          for(i in 1:N){
            y[i] ~ dbern(p[i])
            logit(p[i]) <- b0Family[fam[i]] +                     ## Random effect of family
                            bPace[Pace[i]] +                      ## Pace: fast age of rep < 3yrs or slow age of rep 3+
                            bParity[Parity[i]] +                  ## Parity: iteroparous 3+ yrs rep, semelparous <3 yrs
                            bStoch[simtype[i]] +                  ## stochasticity: Asymptotic, demographic, [1] environ [2] environdemo 
                            bStPopSz * StPopSz[i] +               ## founding population size: 1,10,50,100,1000
                            bStage[start[i]] +                    ## founding population stage: seed, seedling 
                            
                            ## Interactions
                            bPaceXParity[Pace[i],Parity[i]] +
                            bPaceXStoch[Pace[i],simtype[i]] +
                            bPaceXStPopSz[Pace[i]] * StPopSz[i] + 
                            bPaceXStage[Pace[i],start[i]] +
                            
                            bParityXStoch[Parity[i],simtype[i]] +
                            bParityXStPopSz[Parity[i]] * StPopSz[i] + 
                            bParityXStage[Parity[i],start[i]] +
                            
                            bStPopSzXStoch[simtype[i]] * StPopSz[i] +
                            bStageXStoch[start[i],simtype[i]] +
                            
                            bStageXStPopSz[start[i]] * StPopSz[i]
                            
          }
        
        # Priors 
        mu_int ~ dnorm(0, 0.0001) # mean hyperparameter for random intercepts
        sigma_int ~ dunif(0,100)  # SD hyperparameter for random intercepts
        tau_int <- 1/(sigma_int * sigma_int)  ## precision
        ## Random effect of Family
        for(i in 1:nFam){
          b0Family[i] ~ dnorm(mu_int, tau_int) ##Random intercepts
        }
        
        for(i in 1:2){
          Pacetemp[i] ~ dnorm(0, 0.01)
        }
        bPace <- Pacetemp - mean(Pacetemp) ## change in centered Pace
        
        for(i in 1:2){
          Paritytemp[i] ~ dnorm(0, 0.01)
        }
        bParity <- Paritytemp - mean(Paritytemp) ## change in centered Pace
                
        for(i in 1:4){
          simtypetemp[i] ~ dnorm(0, 0.01)
        }
        bStoch <- simtypetemp - mean(simtypetemp)
        
        bStPopSz ~ dunif(-3,3)

        for(i in 1:2){
          Stagetemp[i] ~ dnorm(0, 0.01)
        }
        bStage <- Stagetemp - mean(Stagetemp)
        
        for(i in 1:2){
          for(j in 1:2){
            PaceParitytemp[i,j] ~ dnorm(0,0.01)
          }
        }
        bPaceXParity <- PaceParitytemp - mean(PaceParitytemp)
        
        for(i in 1:2){
          for(j in 1:4){
            bPaceXStochtemp[i,j] ~ dnorm(0, 0.01)
          }
        }
        bPaceXStoch <- bPaceXStochtemp - mean(bPaceXStochtemp)
        
        for(i in 1:2){
          PaceXStPopSztemp[i] ~ dnorm(0, 0.01)
        }
        bPaceXStPopSz <- PaceXStPopSztemp - mean(PaceXStPopSztemp)
        
        for(i in 1:2){
          for(j in 1:2){
            PaceStagetemp[i,j] ~ dnorm(0,0.01)
          }
        }
        bPaceXStage <- PaceStagetemp - mean(PaceStagetemp)
        
        for(i in 1:2){
          for(j in 1:4){
            bParityXStochtemp[i,j] ~ dnorm(0, 0.01)
          }
        }
        bParityXStoch <- bParityXStochtemp - mean(bParityXStochtemp)
        
        for(i in 1:2){
          ParityXStPopSztemp[i] ~ dnorm(0, 0.01)
        }
        bParityXStPopSz <- ParityXStPopSztemp - mean(ParityXStPopSztemp)
        
        for(i in 1:2){
          for(j in 1:2){
            ParityStagetemp[i,j] ~ dnorm(0,0.01)
          }
        }
        bParityXStage <- ParityStagetemp - mean(ParityStagetemp)
        
        for(i in 1:4){
          stpopstochtemp[i] ~ dnorm(0, 0.01)
        }
        bStPopSzXStoch <- stpopstochtemp - mean(stpopstochtemp)
         
        for(i in 1:2){
          for(j in 1:4){
            StageXStochtemp[i,j] ~ dnorm(0,0.01)
          }
        }
        bStageXStoch <- StageXStochtemp - mean(StageXStochtemp)
        
        for(i in 1:2){
          StageXStPopSztemp[i] ~ dnorm(0, 0.01)
        }
        bStageXStPopSz <- StageXStPopSztemp - mean(StageXStPopSztemp)

        
        }")
writeLines(model10yearSeed, "popsize10yrsFamilyseed.jags")

jags.dataseed <- list(y = summarySeedSeedling_all$Ext_10yrs, N = nrow(summarySeedSeedling_all),
                  nFam = length(unique(summarySeedSeedling_all$Family)),
                  fam = as.factor(summarySeedSeedling_all$Family),
                  StPopSz = summarySeedSeedling_all$PopulationSizeScaled,        ## continuous, scaled
                  Pace = as.factor(summarySeedSeedling_all$Pace),                ## [1] fast [2] slow
                  Parity = as.factor(summarySeedSeedling_all$Parity),            ## [1] iteroparous [2] semelparous
                  start = as.factor(summarySeedSeedling_all$start),              ## [1] seed [2] seedling
                  simtype = as.factor(summarySeedSeedling_all$simtype))          ## [1] Asymptotic [2] demo [3] environ [4] environdemo

## parameters monitored
parameters <- c("b0Family","sigma_int","bPace","bParity","bStoch","bStPopSz","bStage",
                "bPaceXParity","bPaceXStoch","bPaceXStPopSz","bPaceXStage",
                "bParityXStoch","bParityXStPopSz","bParityXStage",
                "bStageXStoch","bStageXStPopSz",
                "bStPopSzXStoch")
# MCMC settings
ni <- 10000
nt <- 6
nb <- 5000
nc <- 3
# call JAGS from R
res10seedcat <- jags(jags.dataseed, inits = NULL, parameters, 
            "popsize10yrsFamilyseed.jags", n.chains = nc, n.thin = nt, 
            n.iter = ni, n.burnin = nb,
            working.directory = getwd()) 

save(res10seedcat, file = paste("/Rdatas/binomialFamRndm10yrs_seed",Sys.Date(),"..Rdata", sep=""))
print(res10seedcat, digits = 3, max.levels = 5)
## Check convergence 
# trace plots
traplot(res10seedcat, c("sigma_int","bPace","bParity","bStoch","bStPopSz","bStage",
                "bPaceXParity","bPaceXStoch","bPaceXStPopSz","bPaceXStage",
                "bParityXStoch","bParityXStPopSz","bParityXStage",
                "bStageXStoch","bStageXStPopSz",
                "bStPopSzXStoch"))
# posterior distributions
denplot(res10seedcat, c("sigma_int","bPace","bParity","bStoch","bStPopSz","bStage",
                "bPaceXParity","bPaceXStoch","bPaceXStPopSz","bPaceXStage",
                "bParityXStoch","bParityXStPopSz","bParityXStage",
                "bStageXStoch","bStageXStPopSz",
                "bStPopSzXStoch"))


```


10 year seed with continuous shape reproduction
## Test a JAGS mixed effects run    
```{r}
# specify model in BUGS language   
model10yrSeedShape <- 
  paste("
      model {
        # Likelihood:
          for(i in 1:N){
            y[i] ~ dbern(p[i])
            logit(p[i]) <- b0Family[fam[i]] + 
            
                            bPace[Pace[i]] +                      ## Pace: fast age of rep < 3yrs or slow age of rep 3+
                            bStPopSz * StPopSz[i] +  ## scaled and centered, 1, 10, 50, 100, 1000
                            bShapeItero * shapeI[i] +             ## ShapeItero: -0.5 to 0.5, scaled and centered
                            bStage[start[i]] +                    ## founding population stage: seed, seedling                    
                            bStoch[simtype[i]] +                  ## stochasticity: Asymptotic, demographic, [1] environ [2] environdemo
                            
                            bPaceXStPopSz[Pace[i]] * StPopSz[i] +
                            bPaceXShape[Pace[i]] * shapeI[i] +
                            bPaceXStage[Pace[i],start[i]] + 
                            bPaceXStoch[Pace[i],simtype[i]] +
                            
                            bStPopSzXShape * StPopSz[i] * shapeI[i] +
                            bStPopSzXStart[start[i]] * StPopSz[i] +
                            bStPopSzXStoch[simtype[i]] * StPopSz[i] +
                            
                            bShapeXStart[start[i]] * shapeI[i] +
                            bShapeXStoch[simtype[i]] * shapeI[i] +
                            
                            bStageXStoch[start[i],simtype[i]]
                            
          }
        
        # Priors 
        mu_int ~ dnorm(0, 0.0001) # mean hyperparameter for random intercepts
        sigma_int ~ dunif(0,100)  # SD hyperparameter for random intercepts
        tau_int <- 1/(sigma_int * sigma_int)  ## precision
        ## Random effect of Family
        for(i in 1:nFam){
          b0Family[i] ~ dnorm(mu_int, tau_int) ##Random intercepts
        }
        
        for(i in 1:2){
          Pacetemp[i] ~ dnorm(0, 0.01)
        }
        bPace <- Pacetemp - mean(Pacetemp) ## change in centered Pace
                
        bStPopSz ~ dunif(-3,3)
        
        bShapeItero ~ dunif(-3,3)
        
        ## stage seed, seedling
        for(i in 1:2){
          stagetemp[i] ~ dnorm(0, 0.01)
        }
        bStage <- stagetemp - mean(stagetemp)
        
        for(i in 1:4){
          Starttemp[i] ~ dnorm(0, 0.01)
        }
        bStoch <- Starttemp - mean(Starttemp) 
        
        for(i in 1:2){
          PaceXStPopSztemp[i] ~ dnorm(0, 0.01)
        }
        bPaceXStPopSz <- PaceXStPopSztemp - mean(PaceXStPopSztemp)
        
        for(i in 1:2){
          PaceXShapetemp[i] ~ dnorm(0, 0.01)
        }
        bPaceXShape <- PaceXShapetemp - mean(PaceXShapetemp)
        
        for(i in 1:2){
          for(j in 1:2){
            PaceStagetemp[i,j] ~ dnorm(0,0.01)
          }
        }
        bPaceXStage <- PaceStagetemp - mean(PaceStagetemp)
        
        for(i in 1:2){
          for(j in 1:4){
            bPaceXStochtemp[i,j] ~ dnorm(0, 0.01)
          }
        }
        bPaceXStoch <- bPaceXStochtemp - mean(bPaceXStochtemp)

        bStPopSzXShape ~ dunif(-5,5)
        
        for(i in 1:2){
          bStSttemp[i] ~ dnorm(0, 0.01)
        }
        bStPopSzXStart <- bStSttemp - mean(bStSttemp)
                
        for(i in 1:4){
          StPopSzXStochtemp[i] ~ dnorm(0, 0.01)
        }
        bStPopSzXStoch <- StPopSzXStochtemp - mean(StPopSzXStochtemp)
        
        for(i in 1:2){
          bShSttemp[i] ~ dnorm(0, 0.01)
        }
        bShapeXStart <- bShSttemp - mean(bShSttemp)
        
        for(i in 1:4){
          bShStochtemp[i] ~ dnorm(0, 0.01)
        }
        bShapeXStoch <- bShStochtemp - mean(bShStochtemp)
        
        for(i in 1:2){
          for(j in 1:4){
            stagestoch[i,j] ~ dnorm(0, 0.01)
          }
        }
        bStageXStoch <- stagestoch - mean(stagestoch)
      
      }")
writeLines(model10yrSeedShape, "popsize10yrSeedShape.jags")

sumSeedSeedling <- summarySeedSeedling_v2 %>%
  filter(!is.na(ShapeItero))
jags.data <- list(y = sumSeedSeedling$Ext_10yrs, N = nrow(sumSeedSeedling),
                  nFam = length(unique(sumSeedSeedling$Family)),
                  fam = as.factor(sumSeedSeedling$Family),
                  StPopSz = sumSeedSeedling$PopulationSizeScaled,
                  Pace = as.factor(sumSeedSeedling$Pace),
                  start = as.factor(sumSeedSeedling$start),
                  shapeI = sumSeedSeedling$ShapeIteroScaled,
                  simtype = as.factor(sumSeedSeedling$simtype))

## parameters monitored
parameters <- c("bPace","bStPopSz","bShapeItero","bStoch","bStage",
                "bPaceXStPopSz","bPaceXShape","bPaceXStage","bPaceXStoch",
                "bStPopSzXStart","bStPopSzXShape","bStPopSzXStoch",
                "bShapeXStart","bShapeXStoch",
                "bStageXStoch")
# MCMC settings
ni <- 10000
nt <- 6
nb <- 5000
nc <- 3
# call JAGS from R
res10seedshape <- jags(jags.data, inits = NULL, parameters, 
            "popsize10yrSeedShape.jags", n.chains = nc, n.thin = nt, 
            n.iter = ni, n.burnin = nb,
            working.directory = getwd()) 

save(res10seedshape, file = paste("/Rdatas/binomialFamRndm10yrSeedShape",Sys.Date(),".Rdata", sep=""))
print(res10seedshape, digits = 3)
## Check convergence 
# trace plots
traplot(res10seedshape,c("bPace","bStPopSz","bShapeItero","bStoch","bStage",
                "bPaceXStPopSz","bPaceXShape","bPaceXStage","bPaceXStoch",
                "bStPopSzXStart","bStPopSzXShape","bStPopSzXStoch",
                "bShapeXStart","bShapeXStoch",
                "bStageXStoch"))
# posterior distributions
denplot(res10seedshape,c("bPace","bStPopSz","bShapeItero","bStoch","bStage",
                "bPaceXStPopSz","bPaceXShape","bPaceXStage","bPaceXStoch",
                "bStPopSzXStart","bStPopSzXShape","bStPopSzXStoch",
                "bShapeXStart","bShapeXStoch",
                "bStageXStoch"))
```


## Semelparous defined as reproductive for only one year  
10 years Categorical Pace and parity
```{r}
# specify model in BUGS language   
model10yearSeed <- 
  paste("
      model {
        # Likelihood:
          for(i in 1:N){
            y[i] ~ dbern(p[i])
            logit(p[i]) <- b0Family[fam[i]] +                     ## Random effect of family
                            bPace[Pace[i]] +                      ## Pace: fast age of rep < 3yrs or slow age of rep 3+
                            bParity[Parity[i]] +                  ## Parity: iteroparous 3+ yrs rep, semelparous <3 yrs
                            bStoch[simtype[i]] +                  ## stochasticity: Asymptotic, demographic, [1] environ [2] environdemo 
                            bStPopSz * StPopSz[i] +               ## founding population size: 1,10,50,100,1000
                            bStage[start[i]] +                    ## founding population stage: seed, seedling 
                            ## Interactions
                            bPaceXParity[Pace[i],Parity[i]] +
                            bPaceXStoch[Pace[i],simtype[i]] +
                            bPaceXStPopSz[Pace[i]] * StPopSz[i] + 
                            bPaceXStage[Pace[i],start[i]] +
                            
                            bParityXStoch[Parity[i],simtype[i]] +
                            bParityXStPopSz[Parity[i]] * StPopSz[i] + 
                            bParityXStage[Parity[i],start[i]] +
                            
                            bStageXStoch[start[i],simtype[i]] +
                            bStageXStPopSz[start[i]] * StPopSz[i] +
                            
                            bStPopSzXStoch[simtype[i]] * StPopSz[i]
                            
          }
        
        # Priors 
        mu_int ~ dnorm(0, 0.0001) # mean hyperparameter for random intercepts
        sigma_int ~ dunif(0,100)  # SD hyperparameter for random intercepts
        tau_int <- 1/(sigma_int * sigma_int)  ## precision
        ## Random effect of Family
        for(i in 1:nFam){
          b0Family[i] ~ dnorm(mu_int, tau_int) ##Random intercepts
        }
        
        for(i in 1:2){
          Pacetemp[i] ~ dnorm(0, 0.01)
        }
        bPace <- Pacetemp - mean(Pacetemp) ## change in centered Pace
        
        for(i in 1:2){
          Paritytemp[i] ~ dnorm(0, 0.01)
        }
        bParity <- Paritytemp - mean(Paritytemp) ## change in centered Pace
                
        for(i in 1:4){
          simtypetemp[i] ~ dnorm(0, 0.01)
        }
        bStoch <- simtypetemp - mean(simtypetemp)

        for(i in 1:2){
          Stagetemp[i] ~ dnorm(0, 0.01)
        }
        bStage <- Stagetemp - mean(Stagetemp)
        
        for(i in 1:2){
          for(j in 1:2){
            PaceParitytemp[i,j] ~ dnorm(0,0.01)
          }
        }
        bPaceXParity <- PaceParitytemp - mean(PaceParitytemp)
        
        for(i in 1:2){
          for(j in 1:4){
            bPaceXStochtemp[i,j] ~ dnorm(0, 0.01)
          }
        }
        bPaceXStoch <- bPaceXStochtemp - mean(bPaceXStochtemp)

        for(i in 1:2){
          for(j in 1:4){
            bParityXStochtemp[i,j] ~ dnorm(0, 0.01)
          }
        }
        bParityXStoch <- bParityXStochtemp - mean(bParityXStochtemp)
        
        for(i in 1:2){
          for(j in 1:2){
            PaceStagetemp[i,j] ~ dnorm(0,0.01)
          }
        }
        bPaceXStage <- PaceStagetemp - mean(PaceStagetemp)
        
        
        for(i in 1:2){
          PaceXStPopSztemp[i] ~ dnorm(0, 0.01)
        }
        bPaceXStPopSz <- PaceXStPopSztemp - mean(PaceXStPopSztemp)
        
        for(i in 1:2){
          PaceXShapetemp[i] ~ dnorm(0, 0.01)
        }
        bPaceXShape <- PaceXShapetemp - mean(PaceXShapetemp)
        
        for(i in 1:2){
          ParityXStPopSztemp[i] ~ dnorm(0, 0.01)
        }
        bParityXStPopSz <- ParityXStPopSztemp - mean(ParityXStPopSztemp)
        
        for(i in 1:2){
          for(j in 1:2){
            ParityStagetemp[i,j] ~ dnorm(0,0.01)
          }
        }
        bParityXStage <- ParityStagetemp - mean(ParityStagetemp)
         
        for(i in 1:2){
          for(j in 1:4){
            StageXStochtemp[i,j] ~ dnorm(0,0.01)
          }
        }
        bStageXStoch <- StageXStochtemp - mean(StageXStochtemp)
        
        for(i in 1:2){
          StageXStPopSztemp[i] ~ dnorm(0, 0.01)
        }
        bStageXStPopSz <- StageXStPopSztemp - mean(StageXStPopSztemp)
        
        for(i in 1:4){
          StPopSzXStochtemp[i] ~ dnorm(0, 0.01)
        }
        bStPopSzXStoch <- StPopSzXStochtemp - mean(StPopSzXStochtemp)
        
        bStPopSz ~ dunif(-3,3)
        
        }")
writeLines(model10yearSeed, "popsize10yrsFamilyseed.jags")

jags.dataseed <- list(y = summarySeedSeedling_all1$Ext_10yrs, N = nrow(summarySeedSeedling_all1),
                  nFam = length(unique(summarySeedSeedling_all1$Family)),
                  fam = as.factor(summarySeedSeedling_all1$Family),
                  StPopSz = summarySeedSeedling_all1$PopulationSizeScaled,        ## continuous, scaled
                  Pace = as.factor(summarySeedSeedling_all1$Pace),                ## [1] fast [2] slow
                  Parity = as.factor(summarySeedSeedling_all1$Parity),             ## [1] itero [2] semel
                  start = as.factor(summarySeedSeedling_all1$start),              ## [1] seed [2] seedling
                  simtype = as.factor(summarySeedSeedling_all1$simtype))          ## [1] Asymptotic [2] demo [3] environ [4] environdemo

## parameters monitored
parameters <- c("sigma_int","bPace","bParity","bStoch","bStPopSz","bStage",
                "bPaceXParity","bPaceXStoch","bPaceXStPopSz","bPaceXStage",
                "bParityXStoch","bParityXStPopSz","bParityXStage",
                "bStageXStoch","bStageXStPopSz",
                "bStPopSzXStoch")
# MCMC settings
ni <- 10000
nt <- 6
nb <- 5000
nc <- 3
# call JAGS from R
res10seed <- jags(jags.dataseed, inits = NULL, parameters, 
            "popsize10yrsFamilyseed.jags", n.chains = nc, n.thin = nt, 
            n.iter = ni, n.burnin = nb,
            working.directory = getwd()) 
## misnamed res100
save(res10seed, file = paste("C:/Users/DePrengm/OneDrive - Denver Botanic Gardens/P drive/My Documents/UCDenver_phd/Dissertation/Chapter3/Rdatas/semel1_10yrs_seed",Sys.Date(),"..Rdata", sep=""))
print(res10seed, digits = 3)
## Check convergence 
# trace plots
traplot(res10seed, c("sigma_int","bPace","bParity","bStoch","bStPopSz","bStage",
                "bPaceXParity","bPaceXStoch","bPaceXStPopSz","bPaceXStage",
                "bParityXStoch","bParityXStPopSz","bParityXStage",
                "bStageXStoch","bStageXStPopSz",
                "bStPopSzXStoch"))
# posterior distributions
denplot(res10seed, c("sigma_int","bPace","bParity","bStoch","bStPopSz","bStage",
                "bPaceXParity","bPaceXStoch","bPaceXStPopSz","bPaceXStage",
                "bParityXStoch","bParityXStPopSz","bParityXStage",
                "bStageXStoch","bStageXStPopSz",
                "bStPopSzXStoch"))

```

